apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: time-limited-job
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: time-limited-job
    spec:
      activeDeadlineSeconds: 20
      template:
        metadata:
          creationTimestamp: null
        spec:
          activeDeadlineSeconds: 20
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster; sleep 200
            image: busybox
            name: time-limited-job
            resources: {}
          restartPolicy: Never
  schedule: '*/2 * * * *'
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 3
  startingDeadlineSeconds: 30
status: {}


NAME        ROLE             AGE
sa-devops   Role/sa-devops   26s
controlplane:~$ kubectl describe rolebinding sa-devops -n azure-pipeline
Name:         sa-devops
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  Role
  Name:  sa-devops
Subjects:
  Kind            Name       Namespace
  ----            ----       ---------
  ServiceAccount  sa-devops  azure-pipeline