apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:



  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: myvolume
      mountPath: /etc/foo
    resources: {}
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox2
    volumeMounts:
    - name: myvolume
      mountPath: /etc/foo
  volumes:
    - name: myvolume
      emptyDir: {}